### PR TITLE
[WIP] Add no_plotting option

### PR DESCRIPTION
**Pull request by Serabe**
This option would output the data needed for plotting instead of showing
the plot.

This way, the data can be used for plotting it in a different technology
(i.e. JavaScript).

## Why WIP?

This is a test that needs some checking because:

1. I'm not a Python programmer
2. This needs checking for the maintainer.

The idea is to do this with the rest of modes so the exported data can be used by a frontend lib.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@Serabe I would suggest the following things:

1. Use hercules output directly, because Python code does no magic except some basic resampling which you can easily reproduce in JS
2. If you really need JSON, add another output format to hercules
3. Why not loading PB?

**Comment by Serabe** [comment]
1. Only load_main is 86 lines of code that depend on `numpy` and `pandas`. I am not sure it makes sense to replicate that in Go or JS while we only need the output to produce the chart.
2. I need JSON but not from hercules but from labour.
3. JS in the browser cannot load PB the last time we checked. There was a project to doing so using TypeScript but we couldn't make it work then.

**Comment by vmarkovtsev** [comment]
I deleted my comment, can I delete yours now? :-D

**Comment by vmarkovtsev** [comment]
@Serabe I had to slightly refactor the code now, so we've got conflicts.

**Comment by Serabe** [comment]
Rebased. Not sure if I'll have time to finish the rest.

**Comment by dpordomingo** [comment]
@vmarkovtsev ; if I understood it properly, with https://github.com/src-d/hercules/commit/6df9e586517f588780913a862f6e657bc6691523 is provided the JSON feature to _the rest of modes_ as Sergio proposed. Did I understood right?

**Comment by vmarkovtsev** [comment]
Yes and no. I simplified the interface: now if you specify `*. json` output, it will be automatically JSON, including `--mode=all`

**Comment by dpordomingo** [comment]
That's what I understood. Many thanks!

**Pull request closed without merging**
