### PR TITLE
Change -covermode from count to atomic and add -race

### PR DESCRIPTION
**Pull request by vmarkovtsev**
As suggested by @bobheadxi.

Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

### CODE REVIEW

**Comment by bobheadxi** [comment]
Might want to update this for the appveyor configuration as well!

**Comment by vmarkovtsev** [comment]
There is some weird test failure, `TestRenameAnalysisConsume`. I cannot reproduce it locally, and it really sucks. I will have to debug in Travis if the problem persists.

**Comment by vmarkovtsev** [comment]
OK so I found why the removal of the race condition broke the code @bobheadxi 

This is what happens:

1. matchB finds the match, sends finishedB and finished
2. matchA sees finished, returns and sets finishedA - while it's result is empty
3. When we exit the work group, we select on finishedA and finishedB and choose finishedA
4. This means we use the result from matchA which is empty

I am going to fix it here.

**Comment by vmarkovtsev** [comment]
I found the root cause. `diffmatchpatch.DiffMatchPatch` has `DiffTimeout` struct member, which is `time.Second` by default. It stops calculating the diff if the elapsed time exceeds that limit. Everything runs super fast locally, so I never hit that problem before. However, running several threads on a slow, really retarded Travis instance actually hits that limit, and I got invalid diffs inside renames detection.

**Comment by bobheadxi** [comment]
@vmarkovtsev that's interesting, and strange that it didnt occur before. So is the race condition fix definitely not the culprit then?

**Comment by vmarkovtsev** [comment]
Yep, the race condition is not related. `-race -covermode=atomic` adds a tremendous slowdown, which was never tested.

**Comment by vmarkovtsev** [comment]
After all, I have to revert joining the two modes together. One of the tests, `TestBlobsAreCloseBug2`, takes more than 10 min to run, and fails the test suite.

**Comment by vmarkovtsev** [comment]
The race check adds +9 minutes run time in Travis. Solution: check races in appveyor, not in Travis.

**Pull request merged**
